# Generated by Django 2.2.1 on 2019-05-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20190523_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('iso_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='auditor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auditor', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=50)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('address3', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forum.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
